import os

CORPUS_DATA = {
    "research_qc_01.txt": """Quantum computing represents a paradigm shift in processing information, fundamentally differing from classical computing architectures. While traditional computers depend on binary bits—represented as either zeros or ones—quantum systems leverage qubits. These qubits operate on the principles of quantum mechanics, specifically superposition and entanglement. Superposition allows qubits to exist in multiple states simultaneously, effectively enabling them to perform numerous calculations at once. Entanglement, another bizarre yet powerful quantum phenomenon, inextricably links the states of two or more qubits, regardless of the physical distance separating them. Together, these properties promise exponential increases in processing power, especially for specific computational tasks. For instance, simulating complex molecular structures for drug discovery is practically impossible for classical supercomputers due to the sheer number of variables, but it's a natural fit for quantum systems. Furthermore, cryptography and complex optimization problems, such as route planning mapping in global logistics, stand to be revolutionized. The transition to quantum-based systems, however, requires entirely new algorithmic approaches and hardware paradigms. Researchers worldwide are actively competing to develop the first truly scalable and fault-tolerant quantum computer, marking the dawn of a new technological era.""",

    "research_qc_02.txt": """Despite the immense potential of quantum computing, the development of functional, fault-tolerant quantum computers faces significant engineering and theoretical challenges. The most pressing hurdle is quantum decoherence, which refers to the loss of a qubit's quantum state due to interactions with its external environment. Even minute fluctuations in temperature or electromagnetic fields can cause qubits to lose their delicate superposition and entanglement, leading to high error rates in calculations. To combat this, researchers typically cool quantum processors to temperatures near absolute zero, utilizing complex dilution refrigerators. Another major area of research is quantum error correction codes, which are essential for stabilizing calculations and preserving information. These codes require a large number of physical qubits to represent a single, reliable "logical" qubit, drastically increasing the hardware requirements for practical machines. Some teams are exploring alternative architectures, such as topological qubits, which are theoretically more resistant to environmental noise. If these scaling and stability challenges are overcome, the resulting quantum algorithms, such as Shor's algorithm, could easily decrypt current cryptographic standards like RSA. Consequently, the race towards quantum supremacy runs in parallel with an urgent need to develop post-quantum cryptographic methods to secure global data.""",

    "research_qc_03.txt": """The practical applications of quantum computing extending beyond theoretical physics and into commercial industries are becoming increasingly tangible. In the realm of material science, classical computers struggle to simulate the quantum interactions of atoms and molecules accurately. Quantum computers, conversely, handle these variables natively, which could drastically accelerate the discovery of novel materials, such as more efficient battery components or high-temperature superconductors. The pharmaceutical industry is similarly poised for transformation; quantum simulations could accurately model drug-receptor interactions, reducing the time and cost associated with bringing new treatments to the market. Furthermore, financial institutions are heavily investing in quantum algorithms for advanced portfolio optimization, fraud detection, and derivative pricing, aiming to analyze vast amounts of market data and calculate risk with unprecedented speed. Major tech companies and national governments are channeling billions of dollars into quantum research and development, striving to achieve "quantum advantage"—the point at which a quantum device solves a problem that a classical computer practically cannot. This global investment underscores the strategic importance of quantum technologies, which are expected to redefine industrial capabilities and national security infrastructures in the coming decades.""",

    "research_cyber_01.txt": """Modern cybersecurity architectures are undergoing a fundamental transformation, shifting rapidly away from traditional perimeter-based defenses towards zero-trust frameworks. Historically, network security operated on a "castle-and-moat" model, where anyone inside the network was implicitly trusted. However, with the rise of remote work, cloud computing, and sophisticated insider threats, this model has proven insufficient. In a zero-trust architecture, the core principle is "never trust, always verify." No user, device, or application is trusted by default, regardless of whether they are situated inside or outside the corporate network perimeter. Continuous authentication and authorization processes are mandated for every access request. This approach leverages micro-segmentation, dividing the network into smaller, isolated zones to strictly control access and contain potential breaches. Strict access controls, multi-factor authentication (MFA), and least-privilege principles are rigorously implemented. By assuming that the network is already compromised, zero-trust frameworks effectively prevent the lateral movement of threats. This mitigates the impact of potential data breaches and provides enterprise environments with a much more resilient and dynamic security posture against modern cyber threats.""",

    "research_cyber_02.txt": """The landscape of cyber threats has grown increasingly hostile, with ransomware attacks seeing an unprecedented and alarming rise globally. These attacks, which encrypt a victim's data and demand payment for its release, have systematically targeted critical infrastructure, healthcare systems, and educational institutions. The financial and operational devastation caused by these incidents is profound, often leading to extended downtime and the exposure of sensitive data. Threat actors frequently exploit unpatched software vulnerabilities, capitalizing on delays in corporate patch management cycles. Furthermore, they heavily utilize sophisticated social engineering tactics, particularly highly targeted spear-phishing campaigns, to deceive employees and gain initial access to corporate networks. In response to this escalating threat environment, organizations are fundamentally overhauling their security strategies. They are significantly enhancing their incident response plans to ensure rapid recovery and minimal disruption. Additionally, the adoption of AI-driven threat detection systems is becoming standard practice; these technologies can identify anomalous network behaviors and automate defensive measures in real-time, drastically reducing the window of opportunity for attackers to deploy their malicious payloads.""",

    "research_cyber_03.txt": """The rapid proliferation of networked endpoints has exponentially increased the digital attack surface, introducing profound novel vulnerabilities into enterprise architectures. From remote servers to industrial control systems, billions of interconnected endpoints are now online. Unfortunately, many of these assets are manufactured with an emphasis on cost and speed to market, critically lacking robust, built-in security protocols. They often feature hardcoded default passwords and lack mechanisms for seamless software patching, making them exceptionally vulnerable to exploitation by persistent threats. Cybercriminals frequently compromise these vulnerable endpoints, infecting them with malicious code to construct massive botnets. These botnets are then deployed to execute devastating Distributed Denial-of-Service (DDoS) attacks against major internet services and IT infrastructure. Securing the sprawling enterprise ecosystem requires a multi-faceted approach involving IT administrators, security analysts, and regulatory bodies. It necessitates the mandatory implementation of strong encryption standards for data at rest and in transit. Regular, automated software patching must become the industry norm to defend against discovered vulnerabilities promptly. Furthermore, comprehensive network monitoring and rigorous user authentication protocols are essential to detect compromised infrastructure and protect overall operational security within these digital environments.""",

    "research_telemed_01.txt": """Telemedicine has undeniably revolutionized the landscape of healthcare delivery by bridging geographical divides and enabling remote patient tracking. Utilizing digital platforms, secure messaging, and high-quality video conferencing tools, healthcare professionals can now diagnose, monitor, and treat patients without the need for physical, in-person visits. This paradigm shift has significantly enhanced access to essential medical services, proving particularly transformative for individuals residing in rural or medically underserved communities where specialist care is scarce. For routine check-ups, follow-up appointments, and mental health consultations, telemedicine offers unparalleled convenience, eliminating travel time and reducing the stress associated with clinical environments. Moreover, by diverting non-emergency cases to virtual platforms, clinics and hospitals can significantly reduce wait times and alleviate the burden on physical facilities, allowing them to prioritize critical care. While physical examinations remain necessary for certain diagnoses, the preliminary screening and ongoing management facilitated by telehealth platforms have streamlined healthcare workflows. As technology continues to evolve, the integration of telemedicine is poised to become an enduring and central pillar of modern, patient-centric healthcare systems globally.""",

    "research_telemed_02.txt": """The integration of wearable devices with advanced telehealth systems has introduced a new era of proactive and continuous patient monitoring. Smartwatches, fitness trackers, and specialized medical wearables are now capable of tracking vital signs such as heart rate variability, blood pressure, blood glucose levels, and even sleep patterns with clinical-grade accuracy. This real-time, continuous stream of biometric data is transmitted securely to healthcare providers, allowing doctors to proactively manage chronic conditions such as diabetes and hypertension. Instead of relying on episodic data collected during infrequent clinic visits, physicians can analyze trend lines and intervene before a condition escalates into a medical emergency. However, this massive influx of sensitive health tracking data introduces significant challenges. Patient data privacy remains a paramount concern, necessitating stringent cybersecurity measures to protect against breaches. Ensuring strict compliance with regulations like the Health Insurance Portability and Accountability Act (HIPAA) is complex but mandatory for telehealth providers. Furthermore, the secure and reliable transmission of this data over consumer wireless networks requires robust encryption protocols to maintain patient confidentiality and trust in these digital health ecosystems.""",

    "research_telemed_03.txt": """Despite its obvious benefits and rapid global adoption, telemedicine continues to face substantial implementation barriers related to digital literacy, infrastructure, and policy. A significant portion of the population, particularly the elderly and socioeconomically disadvantaged groups, lack the necessary access to reliable high-speed internet, smartphones, or computers. Even when hardware is available, inadequate digital literacy skills can make navigating complex virtual healthcare platforms daunting and ineffective. This digital divide threatens to exacerbate existing health inequities rather than resolve them. Additionally, the regulatory landscape governing telehealth is fragmented and often outdated. Policies determining insurance reimbursement coverage, state licensing requirements for cross-border medical practice, and the prescribing of medications online vary widely across different jurisdictions. This lack of standardization complicates the operations of telehealth providers and creates confusion for patients seeking coverage. For virtual care practices to become universally established and sustainable, policymakers must enact comprehensive reforms that mandate equitable reimbursement parity, invest in broadband infrastructure for rural areas, and standardize medical licensing across regions, ensuring that telemedicine's promises are accessible to all."""
}

def generate_text_corpus(target_folder="research_documents"):
    os.makedirs(target_folder, exist_ok=True)

    for doc_title, text_body in CORPUS_DATA.items():
        file_path = os.path.join(target_folder, doc_title)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(text_body)

    print(f"Dataset successfully created in '{target_folder}' with {len(CORPUS_DATA)} text files.")

if __name__ == "__main__":
    generate_text_corpus()